# -*- coding: utf-8 -*-
"""exp_1_framework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dV-z2HKtrA_QpgcNfDLuR25KCLLY7Gxt
"""

# Create a new notebook for Python

# Write and execute Python code

print("Hello!")


# Demonstrate the application of Jupyter Widgets, Jupyter AI

import ipywidgets as widgets
from IPython.display import display

def on_slider_change(change):
    print(f"Slider value changed to: {change['new']}")

slider = widgets.IntSlider(value=25, min=0, max=100, description='My Slider:')
slider.observe(on_slider_change, names='value')

display(slider)

